### ISSUE TITLE
How to use the code to generate the daily records like you did?

### ISSUE THREAD

**Issue by donenoyes** [yihong0618/2021#16]
I see the .py files used in the repository. I am not a Python Dev but I would like to generate the daily records like you did.

Can you please add a "usage" section with instructions on how to do it?

It will be very helpful. Thank you!

**Comment by yihong0618** [comment]
@donenoyes 

Hi~ Sorry for his late reply.

This is somewhat personal and complex, so maybe I will write a blog to describe it.

These are from api.
![image](https://user-images.githubusercontent.com/15976103/114327929-a8c2a080-9b6d-11eb-89d0-d424e0e2d8c1.png)

These are from issues and GitHub Actions like you see
![image](https://user-images.githubusercontent.com/15976103/114327955-c263e800-9b6d-11eb-9717-3fb67bd75fdd.png)

This is from my other repo -- https://github.com/yihong0618/github-readme-stats
![image](https://user-images.githubusercontent.com/15976103/114327985-d90a3f00-9b6d-11eb-8cad-f5a163464531.png)

If you want to use, you can fork or clone the repo
And make some issues with label like mine.

**Comment by donenoyes** [comment]
Thank you! 

I am waiting for the detailed blog post as well. It would be very useful. Please do it!

**Comment by yihong0618** [comment]
> Thank you!
> 
> I am waiting for the detailed blog post as well. It would be very useful. Please do it!

But I am not sure when I post it, maybe one or two month later.
sorry for that

**Comment by yihong0618** [comment]
@donenoyes 
写了篇介绍文章，In Chinese.
https://github.com/yihong0618/gitblog/issues/209
